L4t 35.6.0 support
madisongh/digsigserver pull request #30
Opened 2024-11-06 20:22 UTC by Islam-Hussein-11

Added Docker Container support for l4t-r35.6.0. Also taken care of unresolved 0016-Update-tegraflash_impl_t234.py.patch and copied tegra-flash-helper with 194/234 suffix to be compatible with digsigserver until digsigserver is updated to handle the new file name based on the l4t-version.

2024-11-06 21:06 UTC, madisongh commented
@Lexmark-chad Would you have some time to look at this, by any chance?

2024-11-06 21:49 UTC, Lexmark-chad commented
> @Lexmark-chad Would you have some time to look at this, by any chance?

Yea, I'll try to take a look at it tomorrow.

2024-11-07 14:01 UTC, Lexmark-chad requested changes
Overall looks good.  Just one small change requested.

2024-11-08 04:28 UTC, Islam-Hussein-11 commented on docker/Dockerfile
Done

2024-11-08 22:04 UTC, Lexmark-chad commented on docker/Dockerfile
I recommend squashing the two `Dockerfile` commits together.

2024-11-09 12:46 UTC, Islam-Hussein-11 commented on docker/Dockerfile
Done

2024-11-09 13:19 UTC, madisongh requested changes
Could you add a Signed-off-by: line to your commits?

And it would be fine to squash these two commits down to one.

Thanks

2024-11-09 15:23 UTC, madisongh approved these changes

2024-11-09 15:24 UTC, merged